steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.'] #builds the docker image in cloudbuild
images:
- 'gcr.io/$PROJECT_ID/gcpdevops' #uploads the image to the artifact registry