apiVersion: apps/v1
kind: Deployment 
metadata:
  name: gke-app-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-app
  template:
    metadata:
      labels:
        app: gke-app
      spec:
        containers:
        - name: gcp-devops-gke
          image: gcr.io/gcp-engineer-389001/gcpdevops:latest
          ports:
            - containerPort: 5000
          env: 
            - name: PORT 
              value: "5000"